# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    tags-ignore:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
    branches:
      - master
      - next
    paths-ignore:
      - 'VERSION'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build --if-present
      - name: Audit
        run: npm audit --production
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        run: npm run unit --if-present -- --coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive code coverage results
        if: matrix.node-version == '14.x'
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Store version
        run: npm run version:update
      - name: Commit version changes
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email '2273103+SkeLLLa@users.noreply.github.com'
          npm run release
      - name: Commit version changes
        if: ${{ github.ref == 'refs/heads/next' }}
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email '2273103+SkeLLLa@users.noreply.github.com'
          npm run release -- --prerelease rc --skip.changelog
